### Useful aliases ###
alias ll='ls -lha'
alias install='brew install'
alias uninstall='brew uninstall'
alias reload='source ~/.zshrc'
alias cat='bat --paging never --theme DarkNeon'
alias ls='eza -l --icons=always'
alias edit-zsh='nvim ~/.zshrc'
alias n='nvim .'
alias c='clear'
alias edit-nvim='nvim ~/.config/nvim'
